# Use the official Golang image with version 1.20
FROM golang:1.20

# Set the working directory inside the container
WORKDIR /app

# Copy the Go application files to the container
COPY . .

# Command to run the Go script
CMD ["go", "run", "main.go"]
