version: '3.0'

services:
    logstash:
        extends:
            file: common.yml
            service: common
        container_name: logstash
        image: logstash:5.6
        volumes:
            - D:\doan_siem\filter\logstash\Parser\etc\logstash\conf.d:/etc/logstash/conf.d
        command: -f /etc/logstash/conf.d/ -r
        environment:
            LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
            XPACK_MONITORING_ENABLED: "false"
        mem_limit: 1g
        network_mode: host